name: shuttle-deploy
on: 
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  deploy-project:
    runs-on: ubuntu-latest
    steps:
      - name: Custom shuttle deploy action
        uses: denytwice/shuttle-deploy@v0.7-alpha
        with:
          deploy-key: ${{ secrets.SHUTTLE_API_KEY }} 
          secrets: |
            DISCORD_TOKEN = '${{ secrets.DISCORD_TOKEN }}'
            SA_CREDENTIALS_PATH = '${{ secrets.SA_CREDENTIALS_PATH }}'
            SPREADSHEET_ID = '${{ secrets.SPREADSHEET_ID }}'
