name: shuttle-deploy
on: 
  push:
    branches: [ "add-github-action" ]
  pull_request:
    branches: [ "add-github-action" ]

jobs:
  deploy-project:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Setup Rust
        uses: ATiltedTree/setup-rust@v1.0.5
        with:
          rust-version: stable

      - name: Install binstall
        uses: cargo-bins/cargo-binstall@main

      - name: Install shuttle
        run: cargo binstall -y cargo-shuttle
