name: Shuttle Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      SHUTTLE_API_KEY: '{{ secrets.SHUTTLE_API_KEY }}'
    steps:
      - uses: shuttle-hq/deploy-action@main
        with:
          deploy-key: ${{ secrets.SHUTTLE_API_KEY }}
          working-directory: "."
          name: "murali"
          cargo-shuttle-version: "0.35.1"
          secrets: |
            API_KEY = '${{ secrets.API_KEY }}'
            DISCORD_TOKEN = '${{ secrets.DISCORD_TOKEN }}'
            SA_CREDENTIALS_PATH = '${{ secrets.SA_CREDENTIALS_PATH }}'
            SPREADSHEET_ID = '${{ secrets.SPREADSHEET_UD }}'
