name: shuttle-deploy
on: 
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  deploy-project:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Environment Setup
        run: mkdir secrets && echo "${{ secrets.MEMBER_DATA }}" > secrets/MemberData.csv && echo "${{ secrets.SA_CREDENTIALS }}" > secrets/sa_credentials.json
        shell: bash

      - name: Debug
        run: ls
        shell: bash

      - name: Custom shuttle deploy action
        uses: denytwice/shuttle-deploy@v0.8-alpha
        with:
          deploy-key: ${{ secrets.SHUTTLE_API_KEY }}
          enable-debug-logging: "true"
          secrets: |
            DISCORD_TOKEN = '${{ secrets.DISCORD_TOKEN }}'
            SPREADSHEET_ID = '${{ secrets.SPREADSHEET_ID }}'
